### ISSUE TITLE
IOS installation not working

### ISSUE THREAD

**Issue by ejkkan** [applanga/applanga-react-native#2]
I've followed the instruction from the README, and the official documentation of the IOS SDK.

After using react-native link, and trying to add the "ApplangaReactNative.xcodeproj" maunally, I end up with the same error:

<img width="1110" alt="skarmavbild 2018-08-21 kl 15 28 32" src="https://user-images.githubusercontent.com/32518962/44404504-49946580-a557-11e8-9281-a4c2781dcae2.png">

**Comment by leonardarnold** [comment]
Hi,
are you using CocoaPods? I am wondering that you add `ApplangaReactNative.xcodeproj` manually. `react-native link` should do exactly this for you. I recently tried without CocoaPods with `react-native-cli: 2.0.1`, `npm: 6.1.0`. And it worked just fine. Please try to unlink applanga with `react-native unlink applanga-react-native`, remove your manual steps regarding applanga-react-native and then link again.

**Comment by ejkkan** [comment]
Hi,
Thanks for getting back to me.

I found the issue. The minimum requirements for opening the file was Xcode 9.3, I was at 9.2.
Don't know if there are any standard version of setting, I have not had this problem with any other project!

Anyways, keep up the good work!

**Comment by leonardarnold** [comment]
Good to hear and good to know! I will keep that in mind.
Best,
Leonard
