### ISSUE TITLE
v0.0.3 build error

### ISSUE THREAD

**Issue by ejkkan** [applanga/applanga-react-native#5]
When trying to update to 0.0.3 it throws this error:
<img width="643" alt="skarmavbild 2018-10-24 kl 12 32 36" src="https://user-images.githubusercontent.com/32518962/47425074-8c5a0000-d789-11e8-8c9e-89e8326734a6.png">

Trying to use dependency "com.applanga.android:Applanga:2.0.95" but it seems that it is not published. Latest published version is "2.0.93"

**Comment by mckn** [comment]
So it is correct inte the repository. But if you do `npm install applanga-react-native@0.0.3` then the version that is published has `android/gradle.build` with a provided dependency on `2.0.93`.

**Comment by applanga-sroemer** [comment]
thanks for the report its fixed in version 0.0.5
