### ISSUE TITLE
Could not invokte draft mode

### ISSUE THREAD

**Issue by ejkkan** [applanga/applanga-react-native#7]
Using version: 0.0.6

trying to call method showDraftModeDialog on Applanga.

Error:
<img width="400" alt="skarmavbild 2018-12-07 kl 11 26 09" src="https://user-images.githubusercontent.com/32518962/49642293-ebf72c80-fa12-11e8-852c-d65200103fe6.png">

**Comment by leonardarnold** [comment]
Hi, can you please try with 0.0.7 again? Check your gradle dependencies to have the newest applanga version
